/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationRegistry {
  export type FeedbackStruct = {
    reviewer: AddressLike;
    score: BigNumberish;
    feedbackURI: string;
    proofOfPayment: BytesLike;
    timestamp: BigNumberish;
    revoked: boolean;
  };

  export type FeedbackStructOutput = [
    reviewer: string,
    score: bigint,
    feedbackURI: string,
    proofOfPayment: string,
    timestamp: bigint,
    revoked: boolean
  ] & {
    reviewer: string;
    score: bigint;
    feedbackURI: string;
    proofOfPayment: string;
    timestamp: bigint;
    revoked: boolean;
  };

  export type ReputationSummaryStruct = {
    totalFeedback: BigNumberish;
    averageScore: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type ReputationSummaryStructOutput = [
    totalFeedback: bigint,
    averageScore: bigint,
    lastUpdated: bigint
  ] & { totalFeedback: bigint; averageScore: bigint; lastUpdated: bigint };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentFeedback"
      | "getAgentFeedback"
      | "getReputation"
      | "hasReviewed"
      | "owner"
      | "renounceOwnership"
      | "reputations"
      | "revokeFeedback"
      | "submitFeedback"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedbackRevoked"
      | "FeedbackSubmitted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentFeedback",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFeedback",
    values: [BigNumberish, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeedbackRevokedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    reviewer: AddressLike,
    feedbackIndex: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    reviewer: string,
    feedbackIndex: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    reviewer: string;
    feedbackIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeedbackSubmittedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    reviewer: AddressLike,
    score: BigNumberish,
    feedbackURI: string,
    proofOfPayment: BytesLike
  ];
  export type OutputTuple = [
    agentId: bigint,
    reviewer: string,
    score: bigint,
    feedbackURI: string,
    proofOfPayment: string
  ];
  export interface OutputObject {
    agentId: bigint;
    reviewer: string;
    score: bigint;
    feedbackURI: string;
    proofOfPayment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentFeedback: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        reviewer: string;
        score: bigint;
        feedbackURI: string;
        proofOfPayment: string;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getAgentFeedback: TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;

  getReputation: TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.ReputationSummaryStructOutput],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalFeedback: bigint;
        averageScore: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  revokeFeedback: TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      score: BigNumberish,
      feedbackURI: string,
      proofOfPayment: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentFeedback"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        reviewer: string;
        score: bigint;
        feedbackURI: string;
        proofOfPayment: string;
        timestamp: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.FeedbackStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [ReputationRegistry.ReputationSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalFeedback: bigint;
        averageScore: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, feedbackIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      score: BigNumberish,
      feedbackURI: string,
      proofOfPayment: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeedbackRevoked"
  ): TypedContractEvent<
    FeedbackRevokedEvent.InputTuple,
    FeedbackRevokedEvent.OutputTuple,
    FeedbackRevokedEvent.OutputObject
  >;
  getEvent(
    key: "FeedbackSubmitted"
  ): TypedContractEvent<
    FeedbackSubmittedEvent.InputTuple,
    FeedbackSubmittedEvent.OutputTuple,
    FeedbackSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FeedbackRevoked(uint256,address,uint256)": TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;
    FeedbackRevoked: TypedContractEvent<
      FeedbackRevokedEvent.InputTuple,
      FeedbackRevokedEvent.OutputTuple,
      FeedbackRevokedEvent.OutputObject
    >;

    "FeedbackSubmitted(uint256,address,uint8,string,bytes32)": TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
    FeedbackSubmitted: TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
