/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MCPPaymentProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchPayment"
      | "getServerEarnings"
      | "isServerRegistered"
      | "owner"
      | "processPayment"
      | "registerServer"
      | "registeredServers"
      | "renounceOwnership"
      | "serverEarnings"
      | "serverNames"
      | "transferOwnership"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentProcessed"
      | "ServerRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchPayment",
    values: [AddressLike[], BigNumberish[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getServerEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isServerRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [AddressLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerServer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredServers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serverEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serverNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "batchPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getServerEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isServerRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredServers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serverEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serverNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    toolName: string,
    mcpServer: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    toolName: string,
    mcpServer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    toolName: string;
    mcpServer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServerRegisteredEvent {
  export type InputTuple = [serverAddress: AddressLike, serverName: string];
  export type OutputTuple = [serverAddress: string, serverName: string];
  export interface OutputObject {
    serverAddress: string;
    serverName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MCPPaymentProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): MCPPaymentProcessor;
  waitForDeployment(): Promise<this>;

  interface: MCPPaymentProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchPayment: TypedContractMethod<
    [
      servers: AddressLike[],
      amounts: BigNumberish[],
      toolNames: string[],
      mcpServers: string[]
    ],
    [void],
    "nonpayable"
  >;

  getServerEarnings: TypedContractMethod<
    [serverAddress: AddressLike],
    [bigint],
    "view"
  >;

  isServerRegistered: TypedContractMethod<
    [serverAddress: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processPayment: TypedContractMethod<
    [
      serverAddress: AddressLike,
      amount: BigNumberish,
      toolName: string,
      mcpServer: string
    ],
    [void],
    "nonpayable"
  >;

  registerServer: TypedContractMethod<
    [serverAddress: AddressLike, serverName: string],
    [void],
    "nonpayable"
  >;

  registeredServers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  serverEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  serverNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchPayment"
  ): TypedContractMethod<
    [
      servers: AddressLike[],
      amounts: BigNumberish[],
      toolNames: string[],
      mcpServers: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getServerEarnings"
  ): TypedContractMethod<[serverAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isServerRegistered"
  ): TypedContractMethod<[serverAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [
      serverAddress: AddressLike,
      amount: BigNumberish,
      toolName: string,
      mcpServer: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerServer"
  ): TypedContractMethod<
    [serverAddress: AddressLike, serverName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredServers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "serverEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "serverNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "ServerRegistered"
  ): TypedContractEvent<
    ServerRegisteredEvent.InputTuple,
    ServerRegisteredEvent.OutputTuple,
    ServerRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentProcessed(address,address,uint256,string,string,uint256)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "ServerRegistered(address,string)": TypedContractEvent<
      ServerRegisteredEvent.InputTuple,
      ServerRegisteredEvent.OutputTuple,
      ServerRegisteredEvent.OutputObject
    >;
    ServerRegistered: TypedContractEvent<
      ServerRegisteredEvent.InputTuple,
      ServerRegisteredEvent.OutputTuple,
      ServerRegisteredEvent.OutputObject
    >;
  };
}
